version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # El buzón por donde el Coche enviará los datos
      - "15672:15672" # El panel de administración web

  coche-simulador:
    build: .
    depends_on:
      - rabbitmq